# SpawnerDrops by MrThePanda
# If you are getting errors from this plugin it is becuase you do not have SilkSpawners installed

percentage: 100 # There is a 1 in this number chance that a spawner will drop